### PR TITLE
Throttle updates

### PR DESCRIPTION
**Pull request by jedwards1211**

### CODE REVIEW

**Comment by rkstar** [comment]
@jedwards1211 there was a merge last night for multiple collection observing which may have caused this conflict with your `aggregate.js` file. if you can pull the latest `master` and resolve the conflict this should be an easy merge.

**Comment by jedwards1211** [comment]
To be honest, it's not a priority for me, I'm not using this package anymore since it doesn't use Meteor 1.5 imports anyway.  You're welcome to copy the code from my package and make a PR though.

**Comment by JcBernack** [comment]
@rkstar I solved the conflict, but I'm also not using this package anymore. If you could test this branch I would merge it.

**Comment by JcBernack** [comment]
Impemented in PR #36

**Pull request closed without merging**
